const ALL_PRODUCTS = [
  // MEN (9)
  {id:'MEN-001',name:'Brown pants',              cat:'Men',price:29.99,stock:42,desc:'100% cotton relaxed fit tee',           img:'Men1.png'},
  {id:'MEN-002',name:'Slim Fit Black',           cat:'Men',price:59.99,stock:28,desc:'Stretch cotton slim chinos',            img:'Men2.png'},
  {id:'MEN-003',name:'Grey Slack',               cat:'Men',price:89.99,stock:3, desc:'Washed blue denim jacket',             img:'Men3.png'},
  {id:'MEN-004',name:'white linen pants',        cat:'Men',price:49.99,stock:17,desc:'Classic Oxford weave shirt',           img:'Men4.png'},
  {id:'MEN-005',name:'Formal Black',             cat:'Men',price:39.99,stock:0, desc:'Lightweight summer linen shorts',      img:'Men5.png'},
  {id:'MEN-006',name:'Blazer',                   cat:'Men',price:79.99,stock:11,desc:'Fine merino crewneck',                 img:'Men6.png'},
  {id:'MEN-007',name:'zig zag',                  cat:'Men',price:44.99,stock:22,desc:'Tapered cotton joggers',               img:'men7.png'},
  {id:'MEN-008',name:'white basic',              cat:'Men',price:34.99,stock:2, desc:'Pique cotton polo',                   img:'men8.png'},
  {id:'MEN-009',name:'Jacket',                   cat:'Men',price:129.99,stock:8,desc:'Single-breasted slim blazer',         img:'men9.png'},
  // MEN ACCESSORIES (9)
  {id:'MAC-001',name:'Glasses',                  cat:'Men Accessories',price:24.99,stock:35,desc:'Genuine leather reversible belt',  img:'Men A.png'},
  {id:'MAC-002',name:'Sunny Glasses',            cat:'Men Accessories',price:19.99,stock:20,desc:'Soft merino wool scarf',           img:'Men A2.png'},
  {id:'MAC-003',name:'Glasses',                  cat:'Men Accessories',price:22.99,stock:0, desc:'Structured 6-panel cap',          img:'Men A3.png'},
  {id:'MAC-004',name:'Leather Bag',              cat:'Men Accessories',price:34.99,stock:14,desc:'Slim bifold genuine leather',      img:'men A4.png'},
  {id:'MAC-005',name:'Bag lethal',               cat:'Men Accessories',price:29.99,stock:9, desc:'UV400 polarised lenses',          img:'men A5.png'},
  {id:'MAC-006',name:'Sling Bag',                cat:'Men Accessories',price:17.99,stock:3, desc:'Ribbed knit cuffed beanie',       img:'menA6.png'},
  {id:'MAC-007',name:'Canvas Shoes',             cat:'Men Accessories',price:21.99,stock:18,desc:'Heavy duty canvas tote',          img:'menA7.png'},
  {id:'MAC-008',name:'Brown formal shoes',       cat:'Men Accessories',price:19.99,stock:2, desc:'Silk blend woven tie',            img:'Men A8.png'},
  {id:'MAC-009',name:'Outgoing shoes',           cat:'Men Accessories',price:14.99,stock:25,desc:'Set of 3 cotton pocket squares',  img:'men A9.png'},
  // WOMEN (9)
  {id:'WOM-001',name:'Floral Wrap Dress',        cat:'Women',price:64.99,stock:19,desc:'Lightweight chiffon wrap dress',     img:'women .png'},
  {id:'WOM-002',name:'White antique',            cat:'Women',price:69.99,stock:31,desc:'Stretch denim skinny fit',          img:'women 2.png'},
  {id:'WOM-003',name:'Knit Blazer',              cat:'Women',price:54.99,stock:4, desc:'Open-front longline cardigan',      img:'women 3.png'},
  {id:'WOM-004',name:'Linen white ',             cat:'Women',price:89.99,stock:7, desc:'Relaxed linen single-breasted',     img:'women 4.png'},
  {id:'WOM-005',name:'Satin Slip Dress',         cat:'Women',price:74.99,stock:0, desc:'Bias-cut satin mini dress',        img:'women 5.png'},
  {id:'WOM-006',name:'Ribbed Tank Bottom',       cat:'Women',price:24.99,stock:45,desc:'Fitted ribbed stretch tank',       img:'women 6.png'},
  {id:'WOM-007',name:'Wide-Leg Trousers',        cat:'Women',price:59.99,stock:13,desc:'High-rise wide leg trousers',      img:'women 7.png'},
  {id:'WOM-008',name:'Black floral dresses',         cat:'Women',price:49.99,stock:2, desc:'Brushed fleece oversized hoodie', img:'women 8.png'},
  {id:'WOM-009',name:'Midi dresses',               cat:'Women',price:44.99,stock:16,desc:'A-line pleated midi skirt',       img:'women 9.png'},
  // WOMEN ACCESSORIES (9)
  {id:'WAC-001',name:'Pearl earrings',            cat:'Women Accessories',price:14.99,stock:28,desc:'Twisted silk knot headband',      img:'women A.png'},
  {id:'WAC-002',name:'Ruby earrings',            cat:'Women Accessories',price:49.99,stock:11,desc:'Pebbled faux-leather crossbody',   img:'women A2.png'},
  {id:'WAC-003',name:'gold Earrings',           cat:'Women Accessories',price:22.99,stock:0, desc:'Freshwater pearl drop earrings',   img:'Women A3.png'},
  {id:'WAC-004',name:'crafted bag',     cat:'Women Accessories',price:27.99,stock:3, desc:'Cat-eye UV400 frames',             img:'Women A4.png'},
  {id:'WAC-005',name:'twin bracelet',               cat:'Women Accessories',price:18.99,stock:16,desc:'Soft wool-blend beret',            img:'women A5.png'},
  {id:'WAC-006',name:'Scarf',             cat:'Women Accessories',price:59.99,stock:8, desc:'Structured top-handle tote',       img:'Women A6.png'},
  {id:'WAC-007',name:'Shoes formal',           cat:'Women Accessories',price:32.99,stock:14,desc:'Gold-plated charm bracelet',        img:'Women A7.png'},
  {id:'WAC-008',name:'academia shoes',               cat:'Women Accessories',price:39.99,stock:6, desc:'Printed 100% silk scarf',          img:'Women A8.png'},
  {id:'WAC-009',name:'dark red shoes',            cat:'Women Accessories',price:12.99,stock:22,desc:'Set of 6 resin hair clips',        img:'Women A9.png'},
  // KIDS (9)
  {id:'KID-001',name:'Tailor',              cat:'Kids',price:19.99,stock:38,desc:'Fun printed cotton tee',              img:'kids.png'},
  {id:'KID-002',name:'Floral',          cat:'Kids',price:34.99,stock:0, desc:'Adjustable strap dungarees',         img:'kids1.png'},
  {id:'KID-003',name:'White Floral',            cat:'Kids',price:29.99,stock:14,desc:'Warm zip-up fleece hoodie',          img:'kids2.png'},
  {id:'KID-004',name:'Zebra',          cat:'Kids',price:24.99,stock:3, desc:'Soft stretch leggings set',         img:'kids4.png'},
  {id:'KID-005',name:'Formal ',            cat:'Kids',price:17.99,stock:22,desc:'Pull-on smart shorts',              img:'kids5.png'},
  {id:'KID-006',name:'dresses',            cat:'Kids',price:44.99,stock:1, desc:'Lightweight warm puffer',          img:'kids6.png'},
  {id:'KID-007',name:'Pinky ',             cat:'Kids',price:22.99,stock:18,desc:'Classic striped polo shirt',        img:'kids7.png'},
  {id:'KID-008',name:'elegent dresses',             cat:'Kids',price:27.99,stock:9, desc:'Multi-pocket cargo shorts',        img:'kids8.png'},
  {id:'KID-009',name:'White',              cat:'Kids',price:19.99,stock:12,desc:'Quick-dry swim trunks',             img:'kids9.png'},
  // KIDS ACCESSORIES (9)
  {id:'KAC-001',name:'Hat set',        cat:'Kids Accessories',price:12.99,stock:30,desc:'Adjustable cotton cap',          img:'kids A1.png'},
  {id:'KAC-002',name:'Clip Hair',                 cat:'Kids Accessories',price:22.99,stock:18,desc:'Colourful printed backpack',      img:'kids A2.png'},
  {id:'KAC-003',name:'Pencil Box',        cat:'Kids Accessories',price:14.99,stock:0, desc:'Fleece-lined winter set',        img:'kids A3.png'},
  {id:'KAC-004',name:'Blue cap',               cat:'Kids Accessories',price:27.99,stock:7, desc:'Rubber pull-on rain boots',      img:'kids A4.png'},
  {id:'KAC-005',name:'Miniso keychain',                cat:'Kids Accessories',price:11.99,stock:2, desc:'Soft knit scarf & glove set',    img:'kids A5.png'},
  {id:'KAC-006',name:'Stictch ',                  cat:'Kids Accessories',price:13.99,stock:24,desc:'Wide brim UV sun hat',           img:'kids A6.png'},
  {id:'KAC-007',name:'Strawberry cap',                cat:'Kids Accessories',price:16.99,stock:15,desc:'Insulated kids lunch bag',        img:'kids A7.png'},
  {id:'KAC-008',name:'Crafted bag',            cat:'Kids Accessories',price:8.99, stock:40,desc:'Pack of 20 colourful hair ties', img:'kids A8.png'},
  {id:'KAC-009',name:'tiger bag',          cat:'Kids Accessories',price:14.99,stock:11,desc:'UV400 flexible frame',           img:'kids A9.png'},
];